# Generated by Django 5.1.7 on 2025-03-22 06:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='Semester',
        ),
        migrations.AddField(
            model_name='classmaterial',
            name='file_name',
            field=models.CharField(default='file', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.CharField(default='desc', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='icon',
            field=models.CharField(default='sun', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='image_path',
            field=models.CharField(default='image', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='name',
            field=models.CharField(default='course', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
