# Generated by Django 5.1.7 on 2025-03-22 14:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_classmaterial_created_at_course_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='course',
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='myapp.course')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialSnippet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('snippet', models.CharField(max_length=5000)),
                ('class_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.classmaterial')),
                ('subcategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.subject')),
            ],
        ),
        migrations.DeleteModel(
            name='MaterialCut',
        ),
        migrations.DeleteModel(
            name='Subcategory',
        ),
    ]
