# Generated by Django 5.1.7 on 2025-03-22 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_question_snippet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='icon',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='image_path',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
