# Generated by Django 5.1.7 on 2025-03-22 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_course_icon_alter_course_image_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='attempted_single_choice',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='single_correct_choice',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_choices',
            field=models.SmallIntegerField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_short_answer',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='snippet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.materialsnippet'),
        ),
    ]
