# Generated by Django 5.1.7 on 2025-03-23 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_question_attempted_single_choice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='mastery',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_choices',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='materials',
            field=models.ManyToManyField(blank=True, to='myapp.classmaterial'),
        ),
    ]
